### PR TITLE
Add initial config schema

### LINKED ISSUE #5: Color options
https://github.com/atom/settings-view/pull/275 will add support for configurable base color options.

@simurai what do you think are a good 5-10 base color options for this theme to use?

### PR DESCRIPTION
**Pull request by kevinsawicki**
PR to add a config schema that will be used to make this theme adjustable once https://github.com/atom/atom/pull/4153 lands.

@simurai What do you think the options should be saturation and contrast?

Closes #5

### CODE REVIEW

**Comment by simurai** [comment]
Awesome! I added saturation and contrast as `<select>`s:

screen shot 2015-01-23 at 10 02 12 pm

One day we could replace them with input range sliders.

Or maybe just have a single color picker that does everything at once. Currently saturation and brightness gets ignored and only the hue is used.

**Comment by simurai** [comment]
Do the settings colors actually update for you? It looks like packages that use the theme's `ui-variables.less` keep the default color that is originally defined here: https://github.com/atom/one-dark-ui/blob/master/styles/ui-variables.less#L6 and not the one changed in the settings.

screen shot 2015-01-23 at 10 55 04 pm

The buttons and the config menu works because it gets overridden from the theme. I guess we could override the whole settings in the theme, but would be impossible to do for all community packages. Could the packages be reloaded with the new color too, or is that problematic (performance or so)?

**Comment by braver** [comment]
Pretty cool stuff. I've been having the same issues simurai describes (in isotope-hi), wondered why some screens wouldn't update with syntax theme changes. I think all stylesheets need to be recompiled with changes to either syntax-variables or ui-variables because package are free to use both and it gets weird otherwise.

Super awesome stuff guys ✨

**Comment by kevinsawicki** [comment]
> It looks like packages that use the theme's ui-variables.less keep the default color

Yeah, noticing this too, looking into it today.

**Comment by kevinsawicki** [comment]
Closing this out, see https://github.com/atom/atom/pull/4153 for more details.

**Pull request closed without merging**
