### PR TITLE
Fix typo in comment for ui-variables.less

### PR DESCRIPTION
**Pull request by tsangkenneth**
New pull request resulting from #119.

### CODE REVIEW

**Comment by tsangkenneth** [comment]
New pull request for you @simurai. Thanks!

**Comment by lee-dohm** [comment]
Would you mind rebasing this so the only commit is the one for fixing the typo? You can do this with `git rebase -i`. After you do that, you can update this PR with `git push -f`.

**Comment by simurai** [comment]
@lee-dohm Do you mean to remove the 2 (`Change tree-view...` + `Revert "Change tree-view...`) commits so the history is cleaner?

Not sure if rebase can do that. Doesn't it need to be a new branch from master and then apply the change manually again or cherry-pick `Fix typo in comment` from this branch?

**Comment by lee-dohm** [comment]
> Do you mean to remove the 2 (Change tree-view... + Revert "Change tree-view...) commits so the history is cleaner?

Yes, that's what I meant. And not so much from a "cleanliness" perspective but a "confusion" perspective :grinning: I was a little confused when "fixing a typo" had commits talking about other things.

 `git rebase -i` (for "interactive") can do this kind of thing. You just have to force push the results. (See [the Git documentation](http://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages). If you just delete the lines for the two commits from the list and select "pick" for the one you want to keep, they will be removed from history.)

**Comment by lee-dohm** [comment]
@tsangkenneth or @simurai we can merge as is too :grinning:

**Comment by simurai** [comment]
:+1: for less "confusion".

@tsangkenneth If you wanna give `git rebase -i` give a try. Or if that doesn't work out, just make a new PR.

**Comment by tsangkenneth** [comment]
Cool, did `git rebase -i` and now it's just the one clean commit. Thanks @lee-dohm!

**Comment by simurai** [comment]
Perfect! :+1:  Thanks.

**Comment by lee-dohm** [comment]
You're welcome @tsangkenneth :grinning: Thanks for helping out!

**Pull request merged**
