### PR TITLE
Style tabs in docks differently

### PR DESCRIPTION
**Pull request by matthewwithanm**
This is a small update that goes along with atom/atom#13977 and changes the color of the active tab.

### CODE REVIEW

**Comment by simurai** [comment]
Just tried out https://github.com/atom/atom/pull/13977.. :heart_eyes_cat:

With this PR, if things like the Settings get moved into a side dock, the tab background wouldn't match anymore because the Setting's background uses the same as `@pane-item-background-color`:

Before | After
--- | ---
screen shot 2017-03-18 at 8 31 18 pm | screen shot 2017-03-18 at 8 31 50 pm

Hmm.. we could:

- Change `@tool-panel-background-color` to be the same as the center (pane) background color.
- Have a different background for Settings (and others) depending if they are in the center or in a side dock
- Introduce a new `@dock-panel-background-color`. Then themes can decide if the center and the sides look the same or not.

Maybe the 3rd (`@dock-panel-background-color`)?

**Comment by matthewwithanm** [comment]
Wouldn't a new variable be the same situation? Without it, themes can decide if the center and sides look the same or not too. They're just use `@tool-panel-background-color` (which seems preferable).

**Comment by simurai** [comment]
Yeah, `@dock-panel-background-color` was a bad idea. Items inside a dock are still panes and probably should use `@pane-item-background-color`.

Currently the One themes use this:

- Editor: `@syntax-background-color`
- Panes: `@pane-item-background-color` is same as `@syntax-background-color`
- Panels: `@tool-panel-background-color` is a bit darker

Now with the new docks, how about use an in-between color for `@pane-item-background-color`? Regardless if they are in the center or in a dock.

- Editor: `@syntax-background-color`
- Panes (center + docks): `@pane-item-background-color` -> `darken(@syntax-background-color, 3%);`
- Panels: `@tool-panel-background-color` -> `darken(@syntax-background-color, 10%);`

Would look like this:

screen shot 2017-03-21 at 8 26 45 pm

**Comment by matthewwithanm** [comment]
I actually think that they should use `@tool-background-color`. I feel like it identifies them as "tools" more (like current panels) and separates the docks from splits. For example, the console and file tree in Nuclide here:

screen shot 2017-03-21 at 3 47 17 pm

Although I should probably say that Nuclide styles some of these things differently when they're outside of docks (like the console's top bar):

screen shot 2017-03-21 at 3 48 47 pm

imo things like the settings and styleguide exist in a kind of weird middle ground. They aren't tools per se, but you also want to set them apart from editors. For those, I think it's fine to use the middle shade.

**Comment by simurai** [comment]
> Although I should probably say that Nuclide styles some of these things differently when they're outside of docks (like the console's top bar):

I see, yeah, that would also be an option. Although ideally package authors shouldn't have to worry about it. Maybe core/themes also can change of of `.panel-heading` depending where they are.

Ok, how about we merge this for now and I'll make some follow-up PR(s) for things like settings, styleguide, about etc. maybe those that are more likely to be dragged between center and the docks.

And probably also shrink the tabs a bit too. And another thing to consider is the compact/spacious mode. It's neat, but also makes things more complicated. Maybe only have the compact mode.

**Comment by matthewwithanm** [comment]
> Maybe core/themes also can change of of .panel-heading depending where they are.

Ooh yeah, a class or mixin would work.

> And probably also shrink the tabs a bit too.

❤️

Thanks so much @simurai!!

**Pull request merged**
