### PR TITLE
markdown-preview

### PR DESCRIPTION
**Pull request by simurai**
This styles the `markdown-preview` package so it matches the theme colors.

Before:

screen shot 2015-03-04 at 4 54 12 pm

After:

screen shot 2015-03-04 at 4 52 55 pm

### CODE REVIEW

**Comment by simurai** [comment]
Something I'm not sure..

1. Should it be optional? Or a setting to turn it off.
2. Should it rather be an option of `markdown-preview` itself? Found this issue about it: https://github.com/atom/markdown-preview/issues/6

**Comment by braver** [comment]
I kinda prefer the preview on a white background. To me that says "website" more that "editor", and I think it should be very obvious that it's not editable. I would make it optional, but part of the mark-down preview to keep it modular and optional for all themes without extra effort.

**Comment by simurai** [comment]
> I kinda prefer the preview on a white background. To me that says "website" more that "editor"

Yeah agreed. On the other hand, if you're in a dark room it could be a bit jarring.

Part of the markdown-preview package seems better fitting. But then it's harder to have seamless tabs. UI themes wouldn't know what got picked in the settings. hmm.. :neutral_face:

**Comment by braver** [comment]
Gosh darn it you're right! Hmmm...

**Comment by segphault** [comment]
:+1: I think this would be really useful to have as an option. I find it kind of distracting to have the blinding white preview right next to the dark markdown pane while I'm writing.

**Comment by simurai** [comment]
Ok, how about making the markdown preview pane a *bit* lighter than the editor? That way...

- it reduces "blinding"
- there is still a visual difference between input and preview.

screen shot 2015-03-12 at 11 56 07 am

**Comment by braver** [comment]
Looks good! I also realize I'm a light ui guy, but I can see how having a white preview next to an almost black editor is a bit much.

**Comment by segphault** [comment]
That looks really great, it strikes a good balance.

**Comment by simurai** [comment]
Alright, I'll merge this. I think it's fine if there is no option to switch back to the original since that was also an "opinionated" look.

**Pull request merged**
