### PR TITLE
Add SF UI Text

### PR DESCRIPTION
**Pull request by steverandy**
This theme looks lovely with SF font.

screenshot 2015-06-28 01 13 27

### CODE REVIEW

**Comment by thomasjo** [comment]
Thanks for contributing, but I highly doubt we're going to change the UI fonts since the current set matches OS defaults (for the most part), in addition this PR does not actually introduce the font, so this will only work for those that actually have it installed. I'll leave the final decision up to @simurai and the rest of maintainers, but I'm :-1: on merging this.

/cc @atom/feedback

**Comment by 50Wliu** [comment]
:-1: as well.

**Comment by mnquintana** [comment]
@50Wliu @thomasjo Just for some context, this font is San Francisco UI – [Apple's new default OS font for El Capitan](https://developer.apple.com/fonts/) (replacing Helvetica Neue / Lucida Grande on older versions of OS X). Since this is going to be the new default font for OS X (and not just some random font), I'm completely :+1: for this. We should add this to One Light, the Atom themes, and Atom core too.

**Comment by thomasjo** [comment]
Oh, in that case I apologize. Guess I should have done better research. Since this will be a new os default I'm :+1:

**Comment by 50Wliu** [comment]
Sounds good then.

**Comment by simurai** [comment]
I think it's a good addition. El Capitan should come this fall, but for those that installed the SF font can already test it now.

@steverandy Thanks.

**Pull request merged**
